server:
  port: 8080
spring:
  application:
    name: "CT_Container_ConfigMol_EC_MS"
  devtools:
    add-properties: false
  h2:
    console:
      enabled: true
      path: "/h2"
  profiles:
    include: null
aws:
  dynamodb:
    endpoint: "http://localhost:8000"
    tableNameParameter: "${TABLE_NAME_PARAMETER}"
    tableNameConfigMol: "${TABLE_NAME_CONFIG_MOL}"
  endpoint:
    health:
      probes:
        enabled: true